language: rust

rust:
  - stable

os: 
  - linux

dist: bionic

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libsqlcipher-dev
      - libsqlcipher0
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

before_script:
    - bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)

script:
    - cargo build --verbose
    - cargo tarpaulin --out Xml
    - bash <(curl -s https://codecov.io/bash)
