[package]
name = "clinte"
version = "0.1.0"
authors = ["Ben Morrison <ben@gbmor.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "^0.4"
clap = "^2.33"
log = "^0.4"
rand = "^0.7"
rusqlite = "^0.20"
simplelog = "^0.7"